executable = condor_condor-fT0.sh
should_transfer_files = YES
transfer_input_files =/afs/cern.ch/user/y/yian/work/PKU-Cluster/AQGC/2016/run/combine/test/wpwp_fT0_scaling_refined.root
output                = condor-fT0.$(ClusterId).$(ProcId).out
error                 = condor-fT0.$(ClusterId).$(ProcId).err
log                   = condor-fT0.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)


queue 21

