void run(TString sample, TString type){
    TString dir="./"+sample+"/";
    TFile*f1=new TFile(dir+"16_results.root");
    TFile*f2=new TFile(dir+"17_results.root");
    TFile*f3=new TFile(dir+"18_results.root");
    TH1D*h1=(TH1D*)f1->Get(type);
    TH1D*h2=(TH1D*)f2->Get(type);
    TH1D*h3=(TH1D*)f3->Get(type);
    double hmax=h1->GetMaximum()*3;
    h1->GetYaxis()->SetRangeUser(10,hmax);
    gStyle->SetOptStat(0);
    h1->SetMarkerSize(0);
    h2->SetMarkerSize(0);
    h3->SetMarkerSize(0);
    h3->SetLineColor(kGreen); 
    h2->SetLineColor(kBlue); 
    h1->SetLineColor(2); 
    h1->SetLineWidth(2);
    h2->SetLineWidth(2);
    h3->SetLineWidth(2);
    h1->GetYaxis()->SetTitle(type);
    h1->GetYaxis()->SetTitleSize(0.1);
    h1->GetYaxis()->SetTitleOffset(0.4);
//    h1->GetYaxis()->SetTitleFont(20);
    const int num=h1->GetNbinsX();
    TString Xname[12]={"lepton","#gamma^{#eta}","#gamma^{pev}","#gamma^{p_{T}}","#gamma^{hoe}","#gamma^{chiso}","#gamma^{nhiso}","#gamma^{phoiso}","#eta^{j}","p_{T}^{j}","#Delta#eta_{jj}","m_{jj}"};
    TCanvas*c1=new TCanvas("c","",900,600);
    TPad* fPads1 = new TPad("pad1", "", 0.00, 0.40, 0.99, 0.99);
    fPads1->Draw();
    fPads1->SetLogy();
    gStyle->SetPadTickX(1);
    gStyle->SetPadTickY(1);
    gStyle->SetNdivisions(510, "XYZ");
    c1->SetFrameFillColor(41);
    TPad*    fPads2 = new TPad("pad2", "", 0.00, 0.00, 0.99, 0.4);
    fPads1->SetBottomMargin(0);
    fPads2->SetTopMargin(0);
    fPads2->SetBottomMargin(0.3);
    fPads2->Draw();
    fPads1->cd();
    for (int i=0;i<num;i++){
        h1->GetXaxis()->SetBinLabel(i+1,Xname[i]);
    }
    h1->GetXaxis()->SetLabelSize(0.06);
    h1->GetYaxis()->SetLabelSize(0.06); 
    h1->SetTitle("cut flow of "+type);
    h1->Draw();
    h3->Draw("same");
    h2->Draw("same");
    TLegend*l1=new TLegend(0.6,0.6,0.9,0.9);
    l1->AddEntry(h1,"2016 "+sample);
    l1->AddEntry(h2,"2017 "+sample);
    l1->AddEntry(h3,"2018 "+sample);
    l1->Draw();
    fPads1->Update();
    fPads2->cd();
    TH1D*nominal=(TH1D*)h1->Clone("nomimal");
    TH1D*nomNoErr=(TH1D*)nominal->Clone("nomNoErr");
    for (int i = 1; i<= nomNoErr->GetNbinsX(); ++i){nomNoErr->SetBinError(i,0);}
    TH1D*h_up=(TH1D*)h2->Clone();
    TH1D*h_down=(TH1D*)h3->Clone();
    h_up->Divide(nominal);
    h_down->Divide(nominal);
    nominal->GetYaxis()->SetLabelSize(0.06); 
    nominal->Divide(nomNoErr);
    nominal->GetXaxis()->SetLabelSize(0.15); 
    nominal->GetXaxis()->SetLabelOffset(0.02);
    nominal->SetTitle(";[var];ratio");
    nominal->GetXaxis()->SetTitleSize(0.15);
    nominal->GetXaxis()->SetTitleOffset(0.92);
    nominal->GetYaxis()->SetTitleSize(0.12);
    nominal->GetYaxis()->SetTitleOffset(0.25);
    //    nominal->GetYaxis()->SetTitleFont(42);
    nominal->SetFillStyle(3001);
    nominal->SetFillColor(16);
    double max1,max2,max3,min1,min2,min3,max,min;
    max1=1;max2=h_up->GetMaximum();max3=h_down->GetMaximum();
    min1=1;min2=h_up->GetMinimum();min3=h_down->GetMinimum();
    cout<<max1<<" "<<max2<<" "<<max3<<endl;
//    cout<<min1<<" "<<min2<<" "<<min3<<endl;
    if(max2>max1&&max2>max3) max=max2;else max=max3; 
    if(min2<min1&&min2<min3) min=min2;else min=min3;
    cout<<max<<" "<<min<<endl; 
    nominal->GetYaxis()->SetRangeUser(min-0.05,max+0.05);
    nominal->GetYaxis()->SetNdivisions(510);
    TLine* line = new TLine(nominal->GetXaxis()->GetXmin(),1,nominal->GetXaxis()->GetXmax(),1);
    line->SetLineColor(2);
    //    line->Draw();
    nominal->Draw();
    h_up->Draw("EP same");
    h_down->Draw("EP same");
    c1->Print(sample+"Com_"+type+".pdf");
}
int compare(){
    TString type[3]={"entries","yields","eff_entries"};
    for(int i=0;i<3;i++){
        run("EWK",type[i]);
        run("QCD",type[i]);
    }
    return 1;
}
