executable = condor.sh
should_transfer_files = YES
transfer_input_files =/afs/cern.ch/user/y/yian/work/PKU-Cluster/RunII2018/step1_add_weight/SF/2018_ElectronMedium.root,/afs/cern.ch/user/y/yian/work/PKU-Cluster/RunII2018/step1_add_weight/SF/2018_PhotonsMedium.root,/afs/cern.ch/user/y/yian/work/PKU-Cluster/RunII2018/step1_add_weight/SF/EfficienciesStudies_2018_rootfiles_RunABCD_SF_ID.root,/afs/cern.ch/user/y/yian/work/PKU-Cluster/RunII2018/step1_add_weight/SF/EfficienciesStudies_2018_rootfiles_RunABCD_SF_ISO.root,/afs/cern.ch/user/y/yian/work/PKU-Cluster/RunII2018/step1_add_weight/SF/egammaEffi.txt_EGM2D_updatedAll.root
output                = out/condor.$(ClusterId).$(ProcId).out
error                 = err/condor.$(ClusterId).$(ProcId).err
log                   = log/condor.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)
#+JobFlavour = "tomorrow"

queue 

