executable = condor_condor-fT8.sh
arguments = $(state)
should_transfer_files = YES
transfer_input_files =/afs/cern.ch/user/y/yian/work/PKU-Cluster/AQGC/2016/run/combine/test/fT8/wpwp_fT8_scaling_refined.root
output                = out/condor-fT8.$(ClusterId).$(ProcId).out
error                 = err/condor-fT8.$(ClusterId).$(ProcId).err
log                   = log/condor-fT8.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

queue state from list_point_fT8.txt

